name: Build Plugin

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-paper:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew :staffprofiles-paper:build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: staffprofiles-paper
          path: staffprofiles-paper/build/libs/*.jar
  build-velocity:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew :staffprofiles-velocity:build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: staffprofiles-velocity
          path: staffprofiles-velocity/build/libs/*.jar